### ISSUE TITLE
[問題案] Semi-relaxed Convolution

### ISSUE THREAD

**Issue by hly1204** [yosupo06/library-checker-problems#688]
(任意) 問題ID: semi_relaxed_convolution
問題名: Semi-relaxed Convolution

(任意) 想定アルゴリズム: divide and conquer FFT (with some modification) better than O(nlog^2 n)
(任意) 参考資料: Joris. van der Hoeven. [New algorithms for relaxed multiplication](http://www.texmacs.org/joris/newrelax/newrelax.html)

# 問題概要
Same as convolution, but b\_i will be given as soon as c\_i's computation is completed. Maybe we could give the sequence b directly but the real b_i is determined by some xor stuff with known c\_i? (Sorry for my poor English)

It seems that using semi-relaxed convolution to compute exp of fps is faster than using Newton's iteration.

## 入力

```
N M
a_0, a_1, ..., a_{N-1}
b_0, b_1, ..., b_{M-1}
```

## 出力

```
c_0, c_1, ..., c_{N-1+M-1}
```

## 制約

0 <= a\_i, b\_i < 998244353
0 < N, M <= 500000

**Comment by hos-lyric** [comment]
Thanks for raising this issue. I am also curious about how to verify (semi-)relaxed convolution.

----

(1) I think one option is let users use https://judge.yosupo.jp/problem/convolution_mod and guarantee the online-ness in their code. For example, people are using https://judge.yosupo.jp/problem/dynamic_graph_vertex_add_component_sum to verify both offline and online connectivity algorithms (fun fact: the fastest submission is online). Cons for this option are:

- The user has to "guarantee" something by themselves.
- Online solutions will be mixed/hidden in the AC list. I don't think this is very important, but it may be related to the concept of Library-Checker. (@yosupo06 What do you think?)

----

(2) Another option is exactly your proposal of giving b[i] xor c[i - 1] instead of b[i]. I think this is okay, while the problem does not look beautiful in some mathematical sense. And if a user has a code for this version, they can just replace `b[i] ^= c[i-1]` with `write(c[i-1]); read(b[i]);` to have a working code for https://judge.yosupo.jp/problem/convolution_mod.

----

(3) Another option is to have a problem which requires semi-relaxed convolution. The problem shouldn't be too specific. An example I come up with is https://loj.ac/p/575, which might be a bit specific rather than for general purpose. As you mentioned https://judge.yosupo.jp/problem/exp_of_formal_power_series also falls into this category. A downside is that bugs in semi-relaxed might not be caught because of the special properties of such problems.

----

My current feeling is that combination of (1) and (3) (exp) are enough (while not perfect) and (2) is not needed as a separate problem. I highly appreciate further opinions and suggestions!

**Comment by cai-lw** [comment]
I couldn't find comparison of this algorithm with the traditional O(Nlog^2N) method in the paper or anywhere else. How much is it faster than O(Nlog^2N)?

**Comment by hly1204** [comment]
> I couldn't find comparison of this algorithm with the traditional O(Nlog^2N) method in the paper or anywhere else. How much is it faster than O(Nlog^2N)?

A practical method was mentioned by Elegia based on Hoeven's approach with middle product. Dividing the whole problem into B subproblems => T(n)=T(n/B)B+M(n/B)B+Bn take B=logn gives T(n)=O((nlog^2n)/loglogn). There is another bound given by Hoeven in their paper. I think you haven't read the paper yet.

**Comment by cai-lw** [comment]
@hly1204 Sorry for the vague wording of my question. What I wanted to ask is **practical performance**, not theoretic bounds.

Difference by O(loglogN) or even less is hard to be distinguished in competitive programming contexts. So I'm curious about whether (1) it is possible to (2) you are intended to set a limit of N that traditional O(Nlog^2N) cannot pass.

**Comment by hly1204** [comment]
For the semi-relaxed case, I am not sure, maybe 1/2 to 1/3 time of O(nlog^2 n) approach. So I think it is possible to block O(nlog^2 n) algorithm but I am not intended to. My implemention of Hoeven's algorithm runs a little bit faster than my 17E(n) implemention of exp of formal power series. Anyway, this problem is not necessary cause people could test their online/half-line algorithm via existed problems.

**Comment by cai-lw** [comment]
So I implemented the traditional method with `atcoder::convolution` without any optimization and tested on the existing convolution problem. https://judge.yosupo.jp/problem/convolution_mod

* I/O only (133 ms): https://judge.yosupo.jp/submission/59310
* Ordinary convolution (185 ms): https://judge.yosupo.jp/submission/59309
* Traditional O(Nlog^2N) semi-relaxed convolution (799 ms): https://judge.yosupo.jp/submission/59308

From the numbers above, for N=2^19 the traditional method is about 12M(n) (with a lot of overhead of allocating vectors). The benchmark in the paper says about 3M(n) for basically any practical size. So this is at most 4x as fast as the traditional method in the context of competitive programming.

**Comment by hly1204** [comment]
Sorry for my typo above. My implementation <https://judge.yosupo.jp/submission/59399> (509ms) is a little bit slower than my expectition cause it's not designed to solve the problem like this. There will be a lot of useless computation when computing the full product (faster for the truncated producted).
