### ISSUE TITLE
[問題案] Number of Subsequences

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#811]
問題ID: number_of_subsequences
問題名: Number of Subsequences

# 問題概要
長さ N の数列 a_0, a_1, ..., a_{N-1} が与えられる。この数列の相異なる部分列の個数を 998244353 で割った余りを求めよ。

## 入力
```
N
a_0 a_1 ... a_{N-1}
```

## 出力
答えを出力

## 制約
1 <= N <= 500000
1 <= a_i <= 10^9

**Comment by shirotsume4** [comment]
空列は含んだ方がいいでしょうか？

**Comment by SSRS-cp** [comment]
#123 では空列なしになっているので、なしの方がいいと思いました

**Comment by demidenko** [comment]
why this problem exists on Library checker? what algorithm / data structure / general technique it testing?

**Comment by yosupo06** [comment]
Yes, as you said, this problem doesn't verify any libraries, but just a knowledge problem. 

Because I think it is okay to collect knowledge, not only library, technique. In the other hand, I feel this problem maybe ... too easy, but basically increasing problem doesn't have a bad effect on judge (except the storage price for storing testcases).
