### ISSUE TITLE
Enumerate Primes seems to have a problem

### ISSUE THREAD

**Issue by tdkduong** [yosupo06/library-checker-problems#929]
My submission was wrong on the test max_01, and I tried the solution you upload here, it is also wrong. However, I think there is some problem with the test instead.

**Comment by yosupo06** [comment]
Thanks, yeah our judge system had a problem. It was already fixed.

Technical details: we store all judge images, user's exectable file, input file and output file into the ramdisk. Because the size of disk is only 14GB and our judge image size increased, it doesn't have room for store big input / output file.
